mysql:
  host: 127.0.0.1
  port: 3306
  config: ""
  db: gvb-db
  user: root
  password: root
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_Line: false
  log_In_Console: false
system:
  host: 0.0.0.0
  port: 8080
  env: release
site-info:
  created_at: "2023-12-2"
  bei_an: cc
  title: YORE's Blog
  qq_image: ""
  version: 6.0.2
  email: yoreyongwang@gmail.com
  wechat_image: ""
  name: YORE
  job: Full Stack Developer
  addr: Tx, US
  slogan: 食屎呀你
  slogan_en: Fuck this shit
  web: ""
  bilibili_url: ""
  gitee_url: ""
  github_url: ""
  linkedin_url: ""
qq:
  app_id: "123456"
  key: "123456"
  redirect: http://xx.xx.com/login?flag=qq
qi_niu:
  access_key: UMM-xxx-FdRIf-xx
  secret_key: xxx
  bucket: xxx
  cdn: xxx://xxx.xxx.com/
  zone: xxx
  size: "5"
email:
  host: xxx
  port: 0
  user: xxx
  password: xxx
  default_from_email: YORE
  use_ssl: false
  user_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: Sinba
